'use strict';
const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const format='shuati-portable-v1';
const names=['subjects','chapters','questions','removed_groups','sessions','items','wrongs','stars','notes','issues','study_days'];
const kindName={single:'单选',multiple:'多选',judge:'判断',fill:'填空'};
let state=null,db=null,page='home',current='',detailId='',subjectId='',draft={scope:'subject',subject_id:'',chapter_id:'',count:20,order:'fixed',mode:'instant',chapter_start_mode:'unseen',unseen_only:false,weights:{}},queue=Promise.resolve(),messageTimer;
const unpack=value=>typeof value==='string'?JSON.parse(value):value;
const now=()=>Date.now()/1000;
const table=(s,name)=>s.tables[name]||[];
const byId=(rows,id)=>rows.find(row=>row.id===id);
function alertMessage(message,bad=false){const el=$('#message');el.textContent=message;el.className=bad?'error':'';el.hidden=false;clearTimeout(messageTimer);messageTimer=setTimeout(()=>el.hidden=true,5000);}
function fail(error){console.error(error);alertMessage(error.message||String(error),true);}
function openDatabase(){return new Promise((resolve,reject)=>{const req=indexedDB.open('shuati-mobile-v1',1);req.onupgradeneeded=()=>req.result.createObjectStore('data');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
function readDatabase(){return new Promise((resolve,reject)=>{const req=db.transaction('data').objectStore('data').get('state');req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error);});}
function writeDatabase(value){return new Promise((resolve,reject)=>{const tx=db.transaction('data','readwrite');tx.objectStore('data').put(value,'state');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('手机本地保存失败'));});}
function change(fn,redraw=true,silent=false){const next=queue.then(async()=>{const copy=structuredClone(state);const result=fn(copy);await writeDatabase(copy);state=copy;$('#save-status').textContent='已保存到本机';if(redraw)render();return result;});queue=next.catch(()=>{});return next.catch(error=>{if(!silent)fail(error);throw error;});}
function safe(fn){Promise.resolve().then(async()=>{await flushPending();return fn();}).catch(fail);}
function activeSubjects(s=state){const removed=table(s,'removed_groups');return table(s,'subjects').filter(row=>!removed.some(r=>r.kind==='subject'&&r.id===row.id)).sort((a,b)=>a.position-b.position||a.name.localeCompare(b.name));}
function activeChapters(s=state){const removed=table(s,'removed_groups'),subjects=new Set(activeSubjects(s).map(x=>x.id));return table(s,'chapters').filter(row=>subjects.has(row.subject_id)&&!removed.some(r=>r.kind==='chapter'&&r.id===row.id)).sort((a,b)=>a.position-b.position||a.name.localeCompare(b.name));}
function activeQuestions(s=state,practice=true){const chapters=new Set(activeChapters(s).map(x=>x.id));const cs=activeChapters(s),ss=activeSubjects(s);return table(s,'questions').filter(q=>chapters.has(q.chapter_id)&&(!practice||(unpack(q.answer).length&&q.ruling!=='excluded'))).sort((a,b)=>{const ca=byId(cs,a.chapter_id),cb=byId(cs,b.chapter_id),sa=byId(ss,ca.subject_id),sb=byId(ss,cb.subject_id);return sa.position-sb.position||ca.position-cb.position||a.position-b.position||a.id.localeCompare(b.id);});}
function seenIds(s=state){return new Set(table(s,'items').filter(i=>i.correct===0||i.correct===1).map(i=>i.question_id));}
function qdata(row){return {...row,options:unpack(row.options),answer:unpack(row.answer),images:unpack(row.images)};}
function chapterProgress(ch){const questions=activeQuestions().filter(q=>q.chapter_id===ch.id),seen=seenIds();return {total:questions.length,done:questions.filter(q=>seen.has(q.id)).length};}
function photo(src){const name=String(src).split('/').pop();const base=state.media[name];if(!base)return '<p class="muted small">题目配图尚未导入</p>';const ext=name.split('.').pop().toLowerCase();const type={jpg:'jpeg',jpeg:'jpeg',png:'png',webp:'webp',gif:'gif',svg:'svg+xml'}[ext]||'png';return `<img class="figure" src="data:image/${type};base64,${base}" alt="题目配图">`;}
function heading(title,sub=''){return `<h1>${esc(title)}</h1>${sub?`<p class="sub">${esc(sub)}</p>`:''}`;}
function renderHome(){const questions=activeQuestions(),seen=seenIds(),graded=table(state,'items').filter(i=>i.correct===0||i.correct===1),pending=table(state,'sessions').filter(s=>s.status!=='completed').sort((a,b)=>b.updated-a.updated),completed=table(state,'sessions').filter(s=>s.status==='completed').sort((a,b)=>b.completed-a.completed);const subjects=activeSubjects(),next=completed.find(s=>{const cfg=unpack(s.config);return ['subject','chapter','mix'].includes(cfg.scope)&&questions.some(q=>!seen.has(q.id)&&(cfg.scope==='mix'||(byId(table(state,'chapters'),q.chapter_id)?.subject_id===cfg.subject_id&&(cfg.scope!=='chapter'||q.chapter_id===cfg.chapter_id))));});return heading('今天，也向前一点','题库与作答记录保存在这台 iPhone 上。')+
  (pending.length?`<section class="card"><h2>接着上次的进度</h2><p>${esc(unpack(pending[0].config).label||'练习')} · 第 ${pending[0].position+1} 题</p><button class="primary" data-resume="${esc(pending[0].id)}">继续练习</button></section>`:'')+
  (next?`<section class="card"><h2>接着刷未做题</h2><p>${esc(unpack(next.config).label||'上次范围')}</p><button data-next-batch="${esc(next.id)}">设置下一组</button></section>`:'')+
  `<section class="card grid2"><div class="stat">已做不同题<strong>${seen.size}</strong></div><div class="stat">累计判分<strong>${graded.length}</strong></div><div class="stat">正确率<strong>${graded.length?Math.round(graded.filter(i=>i.correct===1).length/graded.length*100)+'%':'—'}</strong></div><div class="stat">可练题目<strong>${questions.length}</strong></div></section><section class="card"><h2>我的科目</h2>${subjects.map(s=>{const cs=activeChapters().filter(c=>c.subject_id===s.id),total=cs.reduce((n,c)=>n+chapterProgress(c).total,0),done=cs.reduce((n,c)=>n+chapterProgress(c).done,0);return `<div class="subject"><div class="row between"><strong>${esc(s.name)}</strong><button data-subject="${esc(s.id)}">查看章节</button></div><div class="progress"><span style="width:${total?done/total*100:0}%"></span></div><span class="small muted">${done} / ${total} 题 · ${cs.length} 章</span></div>`;}).join('')||'<div class="empty">尚无题库。请先到“数据”导入电脑文件。</div>'}</section>`;}
function renderSubject(){const s=byId(table(state,'subjects'),subjectId);if(!s)return renderHome();const cs=activeChapters().filter(c=>c.subject_id===s.id);return heading(s.name,'按章节查看已判分题目进度。')+`<section class="card"><button class="primary" data-quick-subject="${esc(s.id)}">练整个科目</button></section><section class="card"><h2>章节进度</h2>${cs.map(c=>{const p=chapterProgress(c);return `<div class="subject"><div class="row between"><strong>${esc(c.name)}</strong><button data-quick-chapter="${esc(c.id)}" ${p.total?'':'disabled'}>练这一章</button></div><div class="progress"><span style="width:${p.total?p.done/p.total*100:0}%"></span></div><span class="small muted">${p.done} / ${p.total} 题</span></div>`;}).join('')}</section>`;}
function opts(rows,value){return rows.map(row=>`<option value="${esc(row.id)}" ${row.id===value?'selected':''}>${esc(row.name)}</option>`).join('');}
function renderSetup(){const subjects=activeSubjects(),s=byId(subjects,draft.subject_id)||subjects[0];if(s&&!draft.subject_id)draft.subject_id=s.id;const cs=activeChapters().filter(c=>c.subject_id===draft.subject_id);if(!cs.some(c=>c.id===draft.chapter_id))draft.chapter_id=cs[0]?.id||'';const sc=draft.scope;return heading('开始练习','默认按题库顺序；每次作答立即保存。')+`<section class="card"><label class="field">练习范围<select data-draft="scope"><option value="subject" ${sc==='subject'?'selected':''}>单个科目</option><option value="chapter" ${sc==='chapter'?'selected':''}>单个章节</option><option value="mix" ${sc==='mix'?'selected':''}>混合科目</option><option value="wrong" ${sc==='wrong'?'selected':''}>错题复习</option><option value="star" ${sc==='star'?'selected':''}>收藏复习</option></select></label>`+
  (sc==='subject'||sc==='chapter'?`<label class="field">科目<select data-draft="subject_id">${opts(subjects,draft.subject_id)}</select></label>`:'')+
  (sc==='chapter'?`<label class="field">章节<select data-draft="chapter_id">${opts(cs,draft.chapter_id)}</select></label><label class="field">从哪里开始<select data-draft="chapter_start_mode"><option value="unseen" ${draft.chapter_start_mode==='unseen'?'selected':''}>从未做题开始</option><option value="beginning" ${draft.chapter_start_mode==='beginning'?'selected':''}>从头开始</option></select></label>`:'')+
  (sc==='mix'?`<p class="small muted">填写各科比例，合计需为 100%。</p>${subjects.map(s=>`<label class="field">${esc(s.name)} (%)<input type="number" min="0" max="100" inputmode="numeric" data-weight="${esc(s.id)}" value="${draft.weights[s.id]??0}"></label>`).join('')}`:'')+
  (sc!=='chapter'?`<label class="field">本组题数<input type="number" min="1" max="2000" inputmode="numeric" data-draft="count" value="${draft.count}"></label>`:'<p class="small muted">章节练习自动取本章全部题目，选择未做题时会跳过已判分的题。</p>')+
  `<label class="field">题目顺序<select data-draft="order"><option value="fixed" ${draft.order==='fixed'?'selected':''}>题库顺序</option><option value="random" ${draft.order==='random'?'selected':''}>随机顺序</option></select></label><label class="field">判分方式<select data-draft="mode"><option value="instant" ${draft.mode==='instant'?'selected':''}>每题确认后看答案</option><option value="exam" ${draft.mode==='exam'?'selected':''}>交卷后统一判分</option></select></label>`+
  (sc==='subject'||sc==='mix'?`<label class="row small"><input type="checkbox" data-draft="unseen_only" ${draft.unseen_only?'checked':''}> 只刷还未判分的题</label>`:'')+
  `<hr class="divider"><button class="primary" data-start>开始这组练习</button></section>`;}
function getSession(id){return byId(table(state,'sessions'),id);}
function getItems(id){return table(state,'items').filter(i=>i.session_id===id).sort((a,b)=>a.idx-b.idx);}
function answerText(q){if(q.kind==='fill')return q.answer_text||'未提供参考答案';return q.answer.map(n=>`${String.fromCharCode(65+n)}. ${q.options[n]||''}`).join('；');}
function renderPractice(){const session=getSession(current);if(!session){page='home';return renderHome();}const cfg=unpack(session.config),items=getItems(current),item=items[session.position]||items[0];if(!item)return '<div class="card">这组练习没有题目。</div>';const q=unpack(item.snapshot),selected=unpack(item.selected),reveal=!!item.confirmed||session.status==='completed'||(q.kind==='fill'&&selected[1]==='revealed');const note=table(state,'notes').find(n=>n.question_id===q.id)?.body||'';const star=table(state,'stars').some(x=>x.question_id===q.id);const editable=session.status==='active'&&!item.confirmed;return heading(cfg.label||'正在练习',`${session.status==='completed'?'已结束':session.status==='paused'?'已暂停':'进行中'} · 第 ${session.position+1} / ${items.length} 题`)+
  `<section class="card"><div class="chips"><span class="chip">${kindName[q.kind]||q.kind}</span><span class="chip">${esc(q.chapter||'')}</span>${q.ruling==='scope'?'<span class="chip warn">考试口径题</span>':''}</div>${q.ruling==='scope'?`<div class="notice">${esc(q.ruling_note||'按教材考试口径作答')}</div>`:''}<div class="stem">${esc(q.stem)}</div>${(q.images||[]).map(photo).join('')}`+
  (q.kind==='fill'?`<label class="field">你的答案<textarea data-fill ${editable&&selected[1]!=='revealed'?'':'disabled'}>${esc(selected[0]||'')}</textarea></label>${editable&&selected[1]!=='revealed'&&cfg.mode==='instant'?'<button data-fill-reveal>查看参考答案</button>':''}`:
  `<div class="choices">${q.options.map((option,index)=>{const chosen=selected.includes(index),correct=reveal&&q.answer.includes(index);return `<button class="choice ${chosen?'selected':''} ${correct?'correct':''} ${reveal&&chosen&&!correct?'incorrect':''}" data-answer="${index}" ${editable?'':'disabled'}><strong>${String.fromCharCode(65+index)}.</strong> ${esc(option)}</button>`;}).join('')}</div>`)+
  (reveal?`<div class="explain"><strong>参考答案：${esc(answerText(q))}</strong>${item.correct===0?'<p>本题答错</p>':item.correct===1?'<p>本题答对</p>':''}<p>${esc(q.explanation||'暂无解析')}</p></div>`:'')+
  (q.kind==='fill'&&reveal&&!item.confirmed?`<div class="row"><button data-fill-grade="1">我答对了</button><button data-fill-grade="0">我答错了</button></div>`:'')+
  `<div class="practice-actions">${editable&&cfg.mode==='instant'&&q.kind!=='fill'?'<button class="primary" data-confirm>确认本题</button>':''}<button data-star="${esc(q.id)}">${star?'★ 已收藏':'☆ 收藏'}</button></div><label class="field note">我的笔记<textarea data-note="${esc(q.id)}" placeholder="笔记会自动保存">${esc(note)}</textarea></label></section>`+
  `<section class="card"><div class="row between"><h2>答题卡</h2><span class="small muted">${items.filter(i=>i.confirmed).length} / ${items.length} 已判分</span></div><div class="cardnums">${items.map(i=>`<button class="${i.idx===session.position?'current':''} ${i.correct===1?'done':i.correct===0?'wrong':''}" data-jump="${i.idx}">${i.idx+1}</button>`).join('')}</div><div class="practice-actions"><button data-step="-1" ${session.position===0?'disabled':''}>上一题</button><button data-step="1" ${session.position===items.length-1?'disabled':''}>下一题</button></div><div class="practice-actions">${session.status==='active'?'<button data-pause>暂时离开</button>':session.status==='paused'?'<button data-resume-current>继续本组</button>':''}${session.status!=='completed'?'<button data-finish>结束并交卷</button>':''}</div></section>`;}
function renderSet(which){const ids=new Set(table(state,which==='wrong'?'wrongs':'stars').map(x=>x.question_id));const rows=activeQuestions().filter(q=>ids.has(q.id));return heading(which==='wrong'?'错题本':'我的收藏',`共 ${rows.length} 道题`)+`<section class="card"><button class="primary" data-practice-set="${which}" ${rows.length?'':'disabled'}>练习这些题</button>${rows.map(q=>`<div class="item"><div class="badge">${esc(byId(table(state,'chapters'),q.chapter_id)?.name||'')}</div><p>${esc(q.stem.slice(0,110))}</p><div class="row"><button data-detail="${esc(q.id)}">查看题目</button>${which==='wrong'?`<button data-remove-wrong="${esc(q.id)}">移出错题本</button>`:`<button data-star="${esc(q.id)}">取消收藏</button>`}</div></div>`).join('')||'<div class="empty">这里还没有题目。</div>'}</section>`;}
function renderDetail(){const row=byId(table(state,'questions'),detailId);if(!row)return renderHome();const q=qdata(row),note=table(state,'notes').find(n=>n.question_id===q.id)?.body||'',star=table(state,'stars').some(x=>x.question_id===q.id);return heading('题目详情')+`<section class="card"><div class="chips"><span class="chip">${kindName[q.kind]}</span></div><div class="stem">${esc(q.stem)}</div>${q.images.map(photo).join('')}<div class="explain"><strong>参考答案：${esc(answerText(q))}</strong><p>${esc(q.explanation||'暂无解析')}</p></div><button data-star="${esc(q.id)}">${star?'取消收藏':'收藏题目'}</button><label class="field">我的笔记<textarea data-note="${esc(q.id)}">${esc(note)}</textarea></label></section><button data-page="${table(state,'wrongs').some(x=>x.question_id===q.id)?'wrong':'star'}">返回列表</button>`;}
function renderHistory(){return heading('学习记录')+`<section class="card">${[...table(state,'sessions')].sort((a,b)=>b.created-a.created).map(s=>{const items=getItems(s.id),graded=items.filter(i=>i.correct===0||i.correct===1);return `<div class="item"><strong>${esc(unpack(s.config).label||'练习')}</strong><p class="small muted">${new Date(s.created*1000).toLocaleString('zh-CN')} · ${s.status==='completed'?'已结束':'可继续'} · ${graded.length}/${items.length} 题判分</p><button data-open-session="${esc(s.id)}">${s.status==='completed'?'回看':'继续'}</button></div>`;}).join('')||'<div class="empty">暂无练习记录。</div>'}</section>`;}
function renderData(){const q=activeQuestions(state,false).length,items=table(state,'items').length;return heading('数据与迁移','题库、题图和记录都保存在这台手机本地。')+`<section class="card"><h2>本机内容</h2><p>${q} 道题 · ${items} 条作答 · ${table(state,'notes').length} 条笔记 · ${Object.keys(state.media||{}).length} 张配图</p><p class="small muted">${navigator.onLine?'当前设备显示联网':'当前设备显示离线'}。答题不需要网络；每次作答会等本地保存完成。</p></section><section class="card"><h2>与电脑交换文件</h2><p>先在电脑“界面设置”导出文件，传到 iPhone“文件”App，再点这里导入。手机作答后导出文件，回电脑导入。</p><div class="toolbar"><button class="primary" data-import>导入电脑文件</button><button data-export ${q?'':'disabled'}>导出手机记录</button></div><p class="small muted">导入前会检查文件格式，并按编号合并已有作答。导入不会清空手机现有记录。</p></section><section class="card"><h2>安装与离线</h2><p>首次用 Safari 打开 HTTPS 地址，分享 → 添加到主屏幕。导入题库后，可开飞行模式重新打开检查离线状态。</p><label class="field">界面字体大小<input type="range" min="14" max="23" value="${state.font_size||16}" data-font></label><p class="small muted">手机未导出的新记录只存在本机。请定期导出到电脑。</p></section><section class="card"><button data-page="history">查看学习记录</button></section>`;}
function render(){if(!state)return;document.documentElement.style.fontSize=(state.font_size||16)+'px';const content={home:renderHome,subject:renderSubject,setup:renderSetup,practice:renderPractice,wrong:()=>renderSet('wrong'),star:()=>renderSet('star'),detail:renderDetail,history:renderHistory,data:renderData}[page]||renderHome;$('#screen').innerHTML=content();document.querySelectorAll('.tabs button').forEach(button=>button.classList.toggle('active',button.dataset.page===page));}
function go(name){page=name;render();window.scrollTo(0,0);}
document.addEventListener('click',event=>{const id=event.target.closest('[data-next-batch]')?.dataset.nextBatch;if(!id)return;const cfg=unpack(getSession(id).config);Object.assign(draft,{scope:cfg.scope,subject_id:cfg.subject_id||'',chapter_id:cfg.chapter_id||'',count:cfg.count||20,order:cfg.order||'fixed',mode:cfg.mode||'instant',unseen_only:true,chapter_start_mode:'unseen',weights:Object.fromEntries((cfg.weights||[]).map(w=>[w.subject_id,w.value]))});go('setup');});
function shuffle(rows){for(let i=rows.length-1;i>0;i--){const bytes=new Uint32Array(1);crypto.getRandomValues(bytes);const j=bytes[0]%(i+1);[rows[i],rows[j]]=[rows[j],rows[i]];}return rows;}
function makePlan(){let pool=activeQuestions(),sc=draft.scope,subject=byId(table(state,'subjects'),draft.subject_id),chapter=byId(table(state,'chapters'),draft.chapter_id);if(sc==='subject'||sc==='chapter'){if(!subject)throw Error('请选择科目');pool=pool.filter(q=>byId(table(state,'chapters'),q.chapter_id)?.subject_id===subject.id);if(sc==='chapter'){if(!chapter||chapter.subject_id!==subject.id)throw Error('请选择该科目下的章节');pool=pool.filter(q=>q.chapter_id===chapter.id);}}
  if(sc==='wrong'||sc==='star'){const ids=new Set(table(state,sc==='wrong'?'wrongs':'stars').map(x=>x.question_id));pool=pool.filter(q=>ids.has(q.id));}
  const seen=seenIds();if((sc==='chapter'&&draft.chapter_start_mode==='unseen')||(['subject','mix'].includes(sc)&&draft.unseen_only))pool=pool.filter(q=>!seen.has(q.id));let count=sc==='chapter'?pool.length:Math.min(Number(draft.count)||0,pool.length,2000);if(count<1)throw Error('当前范围没有可练题目');if(sc==='mix'){const subjects=activeSubjects(),weights=subjects.map(s=>Number(draft.weights[s.id]||0));if(weights.some(x=>!Number.isFinite(x)||x<0)||Math.abs(weights.reduce((a,b)=>a+b,0)-100)>.001)throw Error('混合科目比例需合计 100%');const raw=weights.map(x=>count*x/100),amounts=raw.map(Math.floor);let extra=count-amounts.reduce((a,b)=>a+b,0);raw.map((x,i)=>({i,part:x-amounts[i]})).sort((a,b)=>b.part-a.part).slice(0,extra).forEach(x=>amounts[x.i]++);const selected=[];subjects.forEach((s,i)=>{const options=pool.filter(q=>byId(table(state,'chapters'),q.chapter_id)?.subject_id===s.id);if(options.length<amounts[i])throw Error(`${s.name} 题量不足，请调整比例或总题量`);selected.push(...(draft.order==='random'?shuffle(options):options).slice(0,amounts[i]));});pool=selected;}else pool=(draft.order==='random'?shuffle(pool):pool).slice(0,count);if(draft.order==='random')shuffle(pool);const label=sc==='mix'?'混合科目练习':sc==='wrong'?'错题复习':sc==='star'?'收藏复习':sc==='chapter'?`${subject.name} / ${chapter.name}`:subject.name;return {pool,label};}
async function startSession(){const {pool,label}=makePlan(),id=crypto.randomUUID(),stamp=now();await change(s=>{table(s,'sessions').forEach(row=>{if(row.status==='active')row.status='paused';});const config={scope:draft.scope,subject_id:draft.subject_id,chapter_id:draft.chapter_id,order:draft.order,mode:draft.mode,count:pool.length,label,chapter_start_mode:draft.chapter_start_mode,unseen_only:draft.unseen_only,weights:activeSubjects().map(x=>({subject_id:x.id,value:Number(draft.weights[x.id]||0)}))};table(s,'sessions').push({id,created:stamp,updated:stamp,completed:null,status:'active',config:JSON.stringify(config),position:0,remaining:null,deadline:null,last_tick:null,elapsed:0});pool.forEach((row,idx)=>{const q=qdata(row),ch=byId(table(s,'chapters'),q.chapter_id),sub=byId(table(s,'subjects'),ch.subject_id);table(s,'items').push({session_id:id,idx,question_id:q.id,snapshot:JSON.stringify({...q,chapter:ch.name,subject:sub.name,subject_id:sub.id}),selected:'[]',confirmed:0,correct:null,scored_at:null});});});current=id;go('practice');}
function score(s,item){if(item.confirmed)return;const q=unpack(item.snapshot),answer=unpack(item.selected);if(q.kind==='fill')return;item.confirmed=1;item.scored_at=now();item.correct=answer.length&&q.answer.length&&q.ruling!=='excluded'&&JSON.stringify([...answer].sort())===JSON.stringify([...q.answer].sort())?1:answer.length?0:null;if(item.correct===0){const old=table(s,'wrongs').find(r=>r.question_id===q.id);if(old){old.mastered=0;old.updated=item.scored_at;}else table(s,'wrongs').push({question_id:q.id,mastered:0,updated:item.scored_at});}else if(item.correct===1){const old=table(s,'wrongs').find(r=>r.question_id===q.id);if(old){old.mastered=1;old.updated=item.scored_at;}}}
async function itemAction(type,value){await change(s=>{const session=byId(table(s,'sessions'),current),item=table(s,'items').find(i=>i.session_id===current&&i.idx===session.position),q=unpack(item.snapshot),selected=unpack(item.selected);if(type==='answer'){if(session.status!=='active'||item.confirmed)throw Error('当前题目不能修改');const index=Number(value);item.selected=JSON.stringify(q.kind==='multiple'?(selected.includes(index)?selected.filter(x=>x!==index):[...selected,index].sort((a,b)=>a-b)):[index]);}else if(type==='confirm'){if(!selected.length)throw Error('请先选择答案');score(s,item);}else if(type==='fill'){if(session.status!=='active'||item.confirmed||selected[1]==='revealed')return;item.selected=JSON.stringify([String(value).slice(0,30000)]);}else if(type==='reveal'){item.selected=JSON.stringify([selected[0]||'','revealed']);}else if(type==='grade'){if(selected[1]!=='revealed')throw Error('请先查看参考答案');item.confirmed=1;item.correct=Number(value);item.scored_at=now();item.selected=JSON.stringify([selected[0]||'','revealed',item.correct?'right':'wrong']);const w=table(s,'wrongs').find(r=>r.question_id===q.id);if(!item.correct){if(w){w.mastered=0;w.updated=item.scored_at;}else table(s,'wrongs').push({question_id:q.id,mastered:0,updated:item.scored_at});}else if(w){w.mastered=1;w.updated=item.scored_at;}}session.updated=now();},type!=='fill');}
async function setPosition(index){await change(s=>{const session=byId(table(s,'sessions'),current);if(index<0||index>=getItems(current).length)return;session.position=index;session.updated=now();});}
async function finishSession(){if(!confirm('结束这组练习？结束后可以回看，不能修改本次作答。'))return;await change(s=>{const session=byId(table(s,'sessions'),current);if(session.status==='completed')return;const cfg=unpack(session.config);for(const item of table(s,'items').filter(i=>i.session_id===current)){if(cfg.mode==='exam')score(s,item);const q=unpack(item.snapshot);if(q.kind==='fill'&&!item.confirmed){const selected=unpack(item.selected);item.selected=JSON.stringify([selected[0]||'','revealed']);}}session.status='completed';session.completed=now();session.updated=session.completed;});}
async function resumeSession(id){await change(s=>{for(const row of table(s,'sessions'))if(row.status==='active')row.status='paused';const session=byId(table(s,'sessions'),id);if(!session)throw Error('找不到练习');if(session.status!=='completed'){session.status='active';session.updated=now();}});current=id;go('practice');}
function mergeRows(local,remote,key){const out=new Map(local.map(row=>[key(row),row]));for(const row of remote)if(!out.has(key(row)))out.set(key(row),row);return [...out.values()];}
function validateFile(data){if(!data||data.format!==format||!data.tables||!Array.isArray(data.tables.questions)||!Array.isArray(data.tables.sessions)||!Array.isArray(data.tables.items)||!data.media||typeof data.media!=='object')throw Error('不是完整的习题簿数据文件');for(const name of names)if(!Array.isArray(data.tables[name]))throw Error('文件缺少 '+name+' 数据');}
function mergeIncoming(s,data,notePolicy=null){validateFile(data);const incoming=data.tables;if(data.source!=='windows')throw Error('手机端请选择电脑导出的文件');const known=new Set(incoming.questions.map(q=>q.id));if(incoming.items.some(i=>!known.has(i.question_id)))throw Error('电脑导出文件中的题目关联有误');const oldSession=new Map(table(s,'sessions').map(row=>[row.id,row]));const oldItem=new Map(table(s,'items').map(row=>[row.session_id+':'+row.idx,row]));const oldNote=new Map(table(s,'notes').map(row=>[row.question_id,row]));const oldStars=new Set(table(s,'stars').map(row=>row.question_id));const oldWrongs=new Map(table(s,'wrongs').map(row=>[row.question_id,row]));
  for(const name of ['subjects','chapters','questions','removed_groups'])s.tables[name]=incoming[name];s.media={...s.media,...data.media};
  for(const row of incoming.sessions){const old=oldSession.get(row.id);if(!old){oldSession.set(row.id,{...row,status:row.status==='completed'?'completed':'paused',last_tick:null});}else if(Number(row.updated)>Number(old.updated)&&old.status!=='active')oldSession.set(row.id,{...row,status:row.status==='completed'?'completed':'paused',last_tick:null});}
  s.tables.sessions=[...oldSession.values()];
  for(const row of incoming.items){const key=row.session_id+':'+row.idx,old=oldItem.get(key);if(!old){oldItem.set(key,row);continue;}if(old.question_id!==row.question_id)throw Error('两端同一题号对应不同题目，已停止导入');if(old.confirmed&&row.confirmed&&(old.selected!==row.selected||old.correct!==row.correct))throw Error('两端同一题有不同的已确认答案，已停止导入');if(!old.confirmed&&row.confirmed)oldItem.set(key,row);}
  s.tables.items=[...oldItem.values()];
  const baseNotes=s.base?.notes||{};const notes=new Map(oldNote);for(const row of incoming.notes){const old=oldNote.get(row.question_id),base=baseNotes[row.question_id];if(!old||old.body===row.body||old.body===base?.body)notes.set(row.question_id,row);else if(row.body!==base?.body){if(!notePolicy)throw Error('两端都修改了同一道题笔记');if(notePolicy==='windows')notes.set(row.question_id,row);}}s.tables.notes=[...notes.values()];
  const changedStars=new Set((s.star_changes||[]).map(x=>x.question_id));const stars=new Map(incoming.stars.map(row=>[row.question_id,row]));for(const id of changedStars){if(oldStars.has(id))stars.set(id,table(s,'stars').find(x=>x.question_id===id));else stars.delete(id);}s.tables.stars=[...stars.values()];
  const changedWrong=new Set((s.wrong_changes||[]).map(x=>x.question_id));const wrongs=new Map(incoming.wrongs.map(row=>[row.question_id,row]));for(const [id,row] of oldWrongs)if(!changedWrong.has(id)&&(!wrongs.has(id)||row.updated>wrongs.get(id).updated))wrongs.set(id,row);for(const id of changedWrong){if(oldWrongs.has(id))wrongs.set(id,oldWrongs.get(id));else wrongs.delete(id);}s.tables.wrongs=[...wrongs.values()];
  s.tables.issues=mergeRows(table(s,'issues'),incoming.issues,row=>row.id);const days=new Map(table(s,'study_days').map(row=>[row.day,row]));for(const row of incoming.study_days){const old=days.get(row.day);days.set(row.day,old?{day:row.day,seconds:Math.max(old.seconds,row.seconds)}:row);}s.tables.study_days=[...days.values()];
  const incomingStars=new Set(incoming.stars.map(row=>row.question_id)),incomingWrongs=new Set(incoming.wrongs.map(row=>row.question_id));
  s.star_changes=(s.star_changes||[]).filter(change=>oldStars.has(change.question_id)!==incomingStars.has(change.question_id));
  s.wrong_changes=(s.wrong_changes||[]).filter(change=>oldWrongs.has(change.question_id)!==incomingWrongs.has(change.question_id));
  s.base={notes:Object.fromEntries(incoming.notes.map(row=>[row.question_id,{body:row.body,updated:row.updated}])),stars:incoming.stars.map(row=>row.question_id),wrongs:incoming.wrongs.map(row=>row.question_id)};s.last_import=now();}
async function importFile(file){if(!file)return;if(file.size>30*1024*1024)throw Error('文件超过 30 MB');const data=JSON.parse(await file.text());validateFile(data);if(data.source!=='windows')throw Error('请选择电脑导出的文件');if(!confirm(`准备导入 ${data.tables.questions.length} 道题、${data.tables.items.length} 条作答记录。已有手机记录会按编号合并。继续吗？`))return;try{await change(s=>mergeIncoming(s,data),true,true);}catch(error){if(!error.message.includes('两端都修改了同一道题笔记'))throw error;const choice=prompt('电脑和手机都修改了同一道题笔记。输入 1 使用电脑版本，输入 2 保留手机版本；点取消停止导入。');if(choice!=='1'&&choice!=='2')return;await change(s=>mergeIncoming(s,data,choice==='1'?'windows':'mobile'));}alertMessage('电脑数据已导入手机');go('home');}
async function exportFile(){await queue;const data={format,source:'mobile',exported_at:now(),tables:state.tables,media:state.media,base:state.base||{},star_changes:state.star_changes||[],wrong_changes:state.wrong_changes||[]};const blob=new Blob([JSON.stringify(data)],{type:'application/json'}),filename='习题簿-手机数据-'+new Date().toISOString().slice(0,10)+'.json',file=new File([blob],filename,{type:'application/json'});if(navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:'习题簿手机数据'});alertMessage('请选择“存储到文件”或传给电脑');return;}catch(error){if(error.name==='AbortError')return;}}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);alertMessage('手机数据已导出，请将文件保存到“文件”并传给电脑');}
let noteTimer,pendingEdit=null;
async function flushPending(){
  if(!pendingEdit)return;
  clearTimeout(noteTimer);
  const edit=pendingEdit;pendingEdit=null;
  if(edit.type==='fill')await itemAction('fill',edit.value);
  else await change(s=>{const rows=table(s,'notes'),old=rows.find(row=>row.question_id===edit.id);if(old){old.body=edit.value;old.updated=now();}else rows.push({question_id:edit.id,body:edit.value,updated:now()});},false);
}
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b||b.disabled)return;safe(async()=>{if(b.dataset.page){go(b.dataset.page);return;}if(b.dataset.subject){subjectId=b.dataset.subject;go('subject');return;}if(b.dataset.quickSubject){draft.scope='subject';draft.subject_id=b.dataset.quickSubject;go('setup');return;}if(b.dataset.quickChapter){draft.scope='chapter';draft.chapter_id=b.dataset.quickChapter;draft.subject_id=byId(table(state,'chapters'),draft.chapter_id).subject_id;go('setup');return;}if(b.dataset.resume){await resumeSession(b.dataset.resume);return;}if(b.dataset.openSession){current=b.dataset.openSession;go('practice');return;}if(b.dataset.resumeCurrent!==undefined){await resumeSession(current);return;}if(b.dataset.practiceSet){draft.scope=b.dataset.practiceSet;go('setup');return;}if(b.dataset.detail){detailId=b.dataset.detail;go('detail');return;}if(b.dataset.start!==undefined){await startSession();return;}if(b.dataset.answer!==undefined){await itemAction('answer',b.dataset.answer);return;}if(b.dataset.confirm!==undefined){await itemAction('confirm');return;}if(b.dataset.fillReveal!==undefined){await itemAction('reveal');return;}if(b.dataset.fillGrade!==undefined){await itemAction('grade',b.dataset.fillGrade);return;}if(b.dataset.jump!==undefined){await setPosition(Number(b.dataset.jump));return;}if(b.dataset.step!==undefined){await setPosition(getSession(current).position+Number(b.dataset.step));return;}if(b.dataset.pause!==undefined){await change(s=>{const row=byId(table(s,'sessions'),current);row.status='paused';row.updated=now();});go('home');return;}if(b.dataset.finish!==undefined){await finishSession();return;}if(b.dataset.star){const id=b.dataset.star;await change(s=>{const rows=table(s,'stars'),index=rows.findIndex(row=>row.question_id===id),value=index<0;if(value)rows.push({question_id:id,created:now()});else rows.splice(index,1);s.star_changes=s.star_changes||[];s.star_changes.push({question_id:id,value,updated:now()});});return;}if(b.dataset.removeWrong){const id=b.dataset.removeWrong;if(!confirm('移出错题本？历史作答仍会保留。'))return;await change(s=>{s.tables.wrongs=table(s,'wrongs').filter(row=>row.question_id!==id);s.wrong_changes=s.wrong_changes||[];s.wrong_changes.push({question_id:id,value:false,updated:now()});});return;}if(b.dataset.import!==undefined){$('#import-file').click();return;}if(b.dataset.export!==undefined){await exportFile();return;}});});
document.addEventListener('change',event=>{const el=event.target;if(el.id==='import-file'){const file=el.files[0];el.value='';safe(()=>importFile(file));return;}if(el.dataset.draft){draft[el.dataset.draft]=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value;if(el.dataset.draft==='subject_id')draft.chapter_id='';if(['scope','subject_id','chapter_id'].includes(el.dataset.draft))render();return;}if(el.dataset.weight){draft.weights[el.dataset.weight]=Number(el.value);return;}if(el.dataset.font!==undefined){safe(()=>change(s=>{s.font_size=Number(el.value);}));return;}});
document.addEventListener('input',event=>{const el=event.target;if(el.dataset.fill!==undefined||el.dataset.note){clearTimeout(noteTimer);$('#save-status').textContent='正在保存…';pendingEdit=el.dataset.fill!==undefined?{type:'fill',value:el.value}:{type:'note',id:el.dataset.note,value:el.value};noteTimer=setTimeout(()=>safe(()=>{}),350);}});
window.addEventListener('pagehide',()=>{const row=getSession(current);if(row&&row.status==='active')safe(()=>change(s=>{const item=byId(table(s,'sessions'),current);item.status='paused';item.updated=now();},false));});
async function init(){try{db=await openDatabase();state=await readDatabase();if(!state){state={format,source:'mobile',tables:Object.fromEntries(names.map(name=>[name,[]])),media:{},base:{notes:{},stars:[],wrongs:[]},star_changes:[],wrong_changes:[],font_size:16};await writeDatabase(state);}if(navigator.serviceWorker)navigator.serviceWorker.register('./sw.js').catch(console.warn);$('#save-status').textContent='已保存到本机';render();}catch(error){fail(error);$('#screen').innerHTML='<div class="card">无法打开手机本地数据库。请检查 Safari 网站数据设置。</div>';}}
init();
